name: fl_downloader
description: A plugin to download files using the native capabilities. URLSession on iOS and DownloadManager on Android
version: 1.0.2
#homepage:
repository: https://github.com/inceptusp/fl_downloader

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.inceptusp.fl_downloader
        pluginClass: FlDownloaderPlugin
      ios:
        pluginClass: FlDownloaderPlugin
